---
- name: configure webserver with nginx
  hosts: webservers
  vars:
    key_file: /etc/nginx/ssl/star.assistanz.com.key
    cert_file: /etc/nginx/ssl/star.assistanz.com.crt
    nginx_conf: /etc/nginx/nginx.conf
    server_name: localhost

  tasks:
    - name: install epel-release
      yum: name=epel-release update_cache=yes

    - name: install nginx
      yum: name=nginx update_cache=yes

    - name: copy conf file with ssl
      copy: src=templates/nginx.conf.j2 dest={{ nginx_conf }}
      notify: restart nginx

    - name: create ssl directories
      file: path=/etc/nginx/ssl state=directory

    - name: copy TLS key
      copy: src=files/star.assistanz.com.key dest={{key_file}} owner=root mode=0600
      notify: restart nginx

    - name: copy TLS cert
      copy: src=files/star.assistanz.com.crt dest={{cert_file}}
      notify: restart nginx

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
